baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

disableKinds = ["taxonomy", "term"]

[menus]
  [[menus.main]]
    name = 'Disaggregate'
    url = '/'
    weight = 10

  [[menus.main]]
    name = 'Posts'
    url = '/posts'
    weight = 20


[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
