baseURL = 'https://disaggregate.pages.dev/'
languageCode = 'en-us'
title = 'Disaggregate'
theme = 'disgoss'
enableRobotsTXT = true

[taxonomies]
  tag = 'tags'

[params]
  description = 'Film, music, and culture reviews.'

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true